local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>fs', builtin.find_files, { desc = 'Telescope find files' })
vim.keymap.set('n', '<leader>gs', builtin.git_files, { desc = 'Telescope find git files' })
vim.keymap.set('n', '<leader>ss', function() 
	builtin.grep_string({ search=vim.fn.input("Grep > ")})
end) 
